name: Deploy_ML
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - requests
  - pip:
    - fastapi==0.63.0
    - uvicorn
    - gunicorn